export const GET_ENTERED_WORDS_SUCCESS = 'GET_ENTERED_WORDS_SUCCESS';
export const GET_DICTIONARY_WORDS_SUCCESS = 'GET_DICTIONARY_WORDS_SUCCESS';
export const ADD_WORD = 'ADD_WORD';
export const UPDATE_WORD_SUCCESS = 'UPDATE_WORD_SUCCESS';